---
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:20.04
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
  config_options:
    defaults:
      allow_broken_conditionals: true
  ansible:
    config_file: ./ansible.cfg
  requirements_file: ./molecule/requirements.yml
verifier:
  name: ansible