---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        # Override defaults for testing - use /tmp for test directories
        rust_gameserver_identity: "test"
        rust_gameserver_port: 28015
        rust_gameserver_rcon_port: 28016
        rust_gameserver_query_port: 28017
        rust_gameserver_rcon_web_port: 28018
        rust_gameserver_app_port: 28083
        rust_gameserver_timezone: "UTC"
        rust_gameserver_wipe_hour_of_day: 12
        rust_gameserver_wipe_day_of_week: 1
        # Skip docker installation since we're testing in CI
        rust_gameserver_molecule_test: true
verifier:
  name: ansible
